#!/bin/sh
# export-agents-md.sh — banto の散文層（thinking-core + rules）をホスト横断標準の AGENTS.md へ機械生成する
#
# 設計: decisions/2026-07-10-070500 (可搬化の第一移植先 = Codex CLI・散文層先行)。
#
# 使い方:
#   export-agents-md.sh [--out <path>] [--host codex|gemini|generic] [--store-base <path>]
#
# 出力名の既定: --host gemini のみ ./GEMINI.md、それ以外（codex/generic）は ./AGENTS.md。
# --out 指定時はそちらを優先する。
#
# 冪等性: タイムスタンプ等の非決定的な値は埋め込まない。同一引数 → 同一出力。
#
# 入力: templates/rules/*.md（BANTO_RULES_DIR で上書き可、既定はこのスクリプトの隣の templates/rules）。
#
# 出力構成: マーカー行 → ヘッダ → thinking-core.md 全文 →
#   quality / safety / evidence-first / spec-fidelity / pii-protection / writing-ja
#   （各ファイルの見出しレベルを 1 段下げて統合） → store 連携フッタ。
#
# 終了コード:
#   0  生成成功
#   2  引数エラー / rules ディレクトリ欠落 / 必須 rule ファイル欠落
#
# POSIX 互換: macOS / Linux / WSL

set -eu

DIR=$(cd "$(dirname "$0")/.." && pwd)
RULES_DIR="${BANTO_RULES_DIR:-$DIR/templates/rules}"

HOST=generic
OUT=""
STORE_BASE=""

while [ $# -gt 0 ]; do
    case "$1" in
        --out)
            [ $# -ge 2 ] || { echo "export-agents-md: --out requires a value" >&2; exit 2; }
            OUT="$2"; shift 2 ;;
        --host)
            [ $# -ge 2 ] || { echo "export-agents-md: --host requires a value" >&2; exit 2; }
            HOST="$2"; shift 2 ;;
        --store-base)
            [ $# -ge 2 ] || { echo "export-agents-md: --store-base requires a value" >&2; exit 2; }
            STORE_BASE="$2"; shift 2 ;;
        *)
            echo "export-agents-md: unknown argument: $1" >&2; exit 2 ;;
    esac
done

case "$HOST" in
    codex|generic|gemini) ;;
    *) echo "export-agents-md: unknown --host ($HOST); use codex|gemini|generic" >&2; exit 2 ;;
esac

if [ -z "$OUT" ]; then
    case "$HOST" in
        gemini) OUT="./GEMINI.md" ;;
        *)      OUT="./AGENTS.md" ;;
    esac
fi

if [ ! -d "$RULES_DIR" ]; then
    echo "export-agents-md: rules directory not found ($RULES_DIR)" >&2
    exit 2
fi

THINKING_CORE="$RULES_DIR/thinking-core.md"
[ -f "$THINKING_CORE" ] || { echo "export-agents-md: thinking-core.md not found ($THINKING_CORE)" >&2; exit 2; }

# 統合対象の rule（この順序で連結。thinking-core は全文のまま別枠で採用する）
RULE_FILES="quality.md safety.md evidence-first.md spec-fidelity.md pii-protection.md writing-ja.md"

for f in $RULE_FILES; do
    [ -f "$RULES_DIR/$f" ] || { echo "export-agents-md: rule file not found ($RULES_DIR/$f)" >&2; exit 2; }
done

# YAML frontmatter（--- ... ---）を除去する。Claude Code の path-scoped 注入専用の記法で、
# 移植先には意味を持たないため。
_strip_frontmatter() {
    awk '
        NR==1 && $0=="---" { infm=1; next }
        infm && $0=="---" { infm=0; next }
        infm { next }
        { print }
    ' "$1"
}

# 見出しレベルを 1 段下げる（行頭が # の行にだけ # を 1 個足す）。
_shift_headings() {
    awk '/^#/ { print "#" $0; next } { print }'
}

{
    printf '<!-- generated by banto export-agents-md — 手編集禁止。再生成: plugins/banto/scripts/export-agents-md.sh --host %s%s --out %s -->\n' \
        "$HOST" "${STORE_BASE:+ --store-base $STORE_BASE}" "$OUT"
    echo
    echo "# AGENTS — banto 散文層のホスト横断出力"
    echo
    echo "banto（Claude Code plugin）の thinking-core + rules をホスト非依存の AGENTS.md 形式へ機械生成した出力。"
    echo "正本は plugins/banto/templates/rules/ 配下。このファイルへの直接編集は次回生成で失われる。"
    echo

    _strip_frontmatter "$THINKING_CORE"
    echo

    for f in $RULE_FILES; do
        _strip_frontmatter "$RULES_DIR/$f" | _shift_headings
        echo
    done

    echo "## store 連携"
    echo
    if [ -n "$STORE_BASE" ]; then
        echo "ai-context store の絶対パス: $STORE_BASE"
        echo "決定・調査・タスクの記録先はこの下（decisions / docs / tasks）。"
    else
        echo "store 連携なし（--store-base 未指定）。決定・調査の記録先は呼び出し側の運用に委ねる。"
    fi
} > "$OUT"

echo "export-agents-md: wrote $OUT" >&2
