#!/bin/sh
# store-map-gen.sh — render the live store map into {base}/meta/store-map.md (idempotent).
#
# Reconciles the manifest (templates/store-layout.json) against filesystem reality and writes a
# single human-readable map: folder ↔ owner skill/hook ↔ scope ↔ gitignore ↔ naming ↔ real count
# ↔ status (ok / missing / lazy-empty). Plus an orphans section (real entries with no owner).
# This is the "全部をマッピング" view; it is regenerated, never hand-edited (like DASHBOARD.md).
#
# Fail-open: jq absent / manifest absent / base unresolved → exit 0 (no map written).
# Usage: store-map-gen.sh [--base <dir>]
set -u

command -v jq >/dev/null 2>&1 || exit 0

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
PLUGIN_ROOT=$(cd -- "$SCRIPT_DIR/.." && pwd)
MANIFEST="$PLUGIN_ROOT/templates/store-layout.json"
[ -f "$MANIFEST" ] || exit 0

BASE=""
[ "${1:-}" = "--base" ] && BASE="${2:-}"
[ -n "$BASE" ] || BASE=$(sh "$PLUGIN_ROOT/scripts/_ai-context-paths.sh" --resolve "$PWD" 2>/dev/null)
[ -n "$BASE" ] && [ -d "$BASE" ] || exit 0

META="$BASE/meta"
OUT="$META/store-map.md"
mkdir -p "$META" 2>/dev/null || exit 0

count_entries() {
    # real file count under a bucket path (dir → files within; file → 0/1)
    p="$1"
    if [ -d "$BASE/$p" ]; then
        find "$BASE/$p" -type f 2>/dev/null | grep -c . | tr -d ' '
    elif [ -e "$BASE/$p" ]; then
        echo 1
    else
        echo 0
    fi
}

TMP=$(mktemp 2>/dev/null || echo "${TMPDIR:-/tmp}/store-map-gen.$$")
trap 'rm -f "$TMP"' EXIT

{
    echo "<!-- AUTO-STORE-MAP: generated by scripts/store-map-gen.sh. Do not edit by hand (overwritten). -->"
    echo "# Store Map — $(basename "$BASE")"
    echo ""
    echo "> フォルダ ↔ 書く skill/hook ↔ scope ↔ gitignore ↔ 命名 ↔ 実体件数 の生きた地図。"
    echo "> 正本マニフェスト: \`templates/store-layout.json\` / 整合チェック: \`store-map-lint.sh\`。"
    echo ""
    echo "| バケット | owner skill/hook | scope | gitignore | 命名 (ERE) | 実体 | 状態 |"
    echo "|---|---|---|---|---|---:|---|"

    jq -r '.buckets[] | [.path, (.owners|join(", ")), .scope, (.gitignore|tostring), (.naming // "—"), (.lazy|tostring)] | @tsv' "$MANIFEST" \
    | while IFS="$(printf '\t')" read -r path owners scope gi naming lazy; do
        cnt=$(count_entries "$path")
        if [ -e "$BASE/$path" ]; then
            [ "$cnt" -gt 0 ] && status="ok" || status="空"
        elif [ "$lazy" = "true" ]; then
            status="lazy（未生成）"
        else
            status="⚠ 欠落"
        fi
        gilabel=$([ "$gi" = "true" ] && echo "ignore" || echo "共有")
        # escape pipes in naming for the table
        naming=$(printf '%s' "$naming" | sed 's/|/\\|/g')
        printf '| `%s` | %s | %s | %s | `%s` | %s | %s |\n' "$path" "$owners" "$scope" "$gilabel" "$naming" "$cnt" "$status"
    done

    echo ""
    echo "## 孤児（実体あり・マニフェスト未登録）"
    echo ""
    # build known top set
    KNOWN=$(jq -r '.buckets[].path' "$MANIFEST" | awk -F/ '{print $1}' | sort -u)
    orphans=""
    for entry in "$BASE"/*; do
        [ -e "$entry" ] || continue
        name=$(basename "$entry")
        case "$name" in .*) continue ;; *-combined.txt) continue ;; esac
        if ! printf '%s\n' "$KNOWN" | grep -qxF "$name"; then
            orphans="$orphans $name"
        fi
    done
    if [ -n "$orphans" ]; then
        for o in $orphans; do echo "- ⚠ \`$o\` — owner 不明。store-layout.json に登録するか掃除する"; done
    else
        echo "（なし — 実体はすべてマニフェストに対応）"
    fi

    echo ""
    echo "## 凡例"
    echo ""
    echo "- **scope**: shared = store git にコミット / personal = \`<author>/\` 名前空間で分離しつつコミット / ephemeral = gitignore（再生成可・per-machine）"
    echo "- **状態**: ok = 実体あり / lazy（未生成）= 特定 skill 初回実行時に生成 / ⚠ 欠落 = 非 lazy なのに実体なし（要調査）"
    echo "- 生成元: \`scripts/store-map-gen.sh\`（SessionStart で日次・冪等再生成）。手で編集しない。"
} > "$TMP"

# idempotent: only overwrite when content changed (mirrors DASHBOARD.md behavior)
if [ -f "$OUT" ] && cmp -s "$TMP" "$OUT"; then
    exit 0
fi
cp "$TMP" "$OUT" 2>/dev/null || exit 0
exit 0
