#!/bin/sh
# test-export-agents-md.sh — export-agents-md.sh の検証
set -u

DIR=$(cd "$(dirname "$0")/.." && pwd)
SCRIPT="$DIR/scripts/export-agents-md.sh"

TMP=$(mktemp -d "${TMPDIR:-/tmp}/export-agents-md-test.XXXXXX")
trap 'rm -rf "$TMP"' EXIT
fail=0
ok()  { printf 'ok   %s\n' "$1"; }
bad() { printf 'FAIL %s\n' "$1"; fail=1; }

# === case 1: 生成物にマーカーと thinking-core の見出しが含まれる ===
OUT1="$TMP/AGENTS.md"
sh "$SCRIPT" --out "$OUT1" >/dev/null 2>&1
[ -f "$OUT1" ] && ok "generic: output file created" || bad "generic: output file missing"
grep -q 'generated by banto export-agents-md' "$OUT1" && ok "marker: present" || bad "marker: missing"
grep -q '^# Thinking Core' "$OUT1" && ok "thinking-core: full text included (unshifted H1)" || bad "thinking-core: heading missing"
grep -q '^## コード品質ルール' "$OUT1" && ok "rules: heading shifted to H2 (quality.md)" || bad "rules: heading not shifted"
grep -q '^## 日本語ライティング・ルール' "$OUT1" && ok "rules: writing-ja included and shifted" || bad "rules: writing-ja missing"

# === case 2: 冪等（同一引数で 2 回実行しても diff なし） ===
cp "$OUT1" "$TMP/AGENTS.before.md"
sh "$SCRIPT" --out "$OUT1" >/dev/null 2>&1
diff -q "$TMP/AGENTS.before.md" "$OUT1" >/dev/null 2>&1 \
    && ok "idempotent: identical output across repeated runs" \
    || bad "idempotent: output changed on re-run"

# === case 3: --store-base 指定時にパスが埋まる / 未指定時は縮退文面 ===
OUT3="$TMP/AGENTS-store.md"
sh "$SCRIPT" --out "$OUT3" --store-base "/tmp/example-store" >/dev/null 2>&1
grep -q '/tmp/example-store' "$OUT3" && ok "store-base: path embedded" || bad "store-base: path missing"
grep -q 'store 連携なし' "$OUT1" && ok "no store-base: degraded message present" || bad "no store-base: degraded message missing"

# === case 4: --host gemini の既定出力名は GEMINI.md（--out 未指定時） ===
( cd "$TMP" && sh "$SCRIPT" --host gemini >/dev/null 2>&1 )
[ -f "$TMP/GEMINI.md" ] && ok "host gemini: default output name is GEMINI.md" || bad "host gemini: default output name wrong"
( cd "$TMP" && sh "$SCRIPT" --host codex >/dev/null 2>&1 )
[ -f "$TMP/AGENTS.md" ] || bad "host codex: default output name is not AGENTS.md (unexpected, pre-existing file check invalid)"

# === case 5: rules ディレクトリ欠落時に非 0 で明確なエラー ===
EMPTY="$TMP/no-rules-dir"
OUT5="$TMP/AGENTS5.md"
ERR5=$(BANTO_RULES_DIR="$EMPTY" sh "$SCRIPT" --out "$OUT5" 2>&1 1>/dev/null)
RC5=$?
[ "$RC5" -ne 0 ] && ok "missing rules dir: non-zero exit ($RC5)" || bad "missing rules dir: exit was 0"
[ ! -f "$OUT5" ] && ok "missing rules dir: no partial output written" || bad "missing rules dir: output file written despite error"
printf '%s' "$ERR5" | grep -qi 'rules directory not found' \
    && ok "missing rules dir: clear error message" \
    || bad "missing rules dir: error message unclear ($ERR5)"

# === case 6: 未知の --host は非 0 でエラー ===
BAD_RC=0
sh "$SCRIPT" --out "$TMP/bad.md" --host claude >/dev/null 2>&1 || BAD_RC=$?
[ "$BAD_RC" -ne 0 ] && ok "unknown --host: non-zero exit" || bad "unknown --host: exit was 0"

[ "$fail" -eq 0 ] && echo "ALL GREEN"
exit "$fail"
