#!/bin/sh
# ai-context-dashboard.sh — 鳥瞰図を <base>/DASHBOARD.md に再生成する
#
# 全 WS 横断の鳥瞰図（🟢 ongoing spec / 📝 本日の decisions / 🌳 worktree / 🗂 WS 一覧）を
# 専用の DASHBOARD.md（per-checkout ローカル・gitignore 対象）に書き出す。
# 旧出力先だった active.md の AUTO-DASHBOARD ブロックは、残存していれば
# 「DASHBOARD.md へ移設」の1行ポインタに置換する（stale な鳥瞰図を残さない）。
# spec: docs/specs/2026-06-04_ai-context-personal-state-separation（論点A=A1）
#
# 冪等: DASHBOARD.md は丸ごと再生成（内容不変なら書き戻さない）。
# 呼び出し: SessionStart hook から、または手動で `ai-context-dashboard.sh <cwd>`
# POSIX互換: macOS / Linux / WSL

CWD="${1:-$PWD}"

# ai-context ベースdir を解決（central/legacy 透過・既定 legacy で挙動不変）
PATHS_DIR=${CLAUDE_PLUGIN_ROOT:+"$CLAUDE_PLUGIN_ROOT/scripts"}
[ -z "$PATHS_DIR" ] && PATHS_DIR=$(cd "$(dirname "$0")/../scripts" 2>/dev/null && pwd)
AI_BASE="$CWD/.ai-context"
if [ -f "$PATHS_DIR/_ai-context-paths.sh" ]; then
    AI_PATHS="$PATHS_DIR/_ai-context-paths.sh"
    . "$AI_PATHS"
    AI_BASE=$(_ai_context_base_dir "$CWD")
fi
[ -d "$AI_BASE" ] || exit 0
command -v git >/dev/null 2>&1 || exit 0
DASHBOARD="$AI_BASE/DASHBOARD.md"
ACTIVE="$AI_BASE/tasks/active.md"

TODAY=$(date +%Y-%m-%d)
DEC_DIR="$AI_BASE/decisions"
SPEC_DIR="$AI_BASE/docs/specs"
WS_DIR="$AI_BASE/workspaces"

# --- ブロック本文を組み立て（一時ファイル） ---
BLOCK=$(mktemp)
{
    echo "<!-- AUTO-DASHBOARD-START : this block is auto-generated by a hook. Manual edits are overwritten on the next regeneration -->"
    echo "## 🛰 Dashboard (auto-generated: ${TODAY})"
    echo ""

    # ongoing spec（docs/specs/ の最新 5 件、_tasks.md を基準に）
    echo "### 🟢 ongoing spec"
    if [ -d "$SPEC_DIR" ]; then
        _specs=$(ls -t "$SPEC_DIR"/*_spec.md 2>/dev/null | head -5)
        if [ -n "$_specs" ]; then
            for f in $_specs; do echo "- $(basename "$f")"; done
        else
            echo "- (none)"
        fi
    else
        echo "- (no docs/specs/)"
    fi
    echo ""

    # 本日の decisions
    echo "### 📝 Today's decisions (${TODAY})"
    if [ -d "$DEC_DIR" ]; then
        _decs=$(ls "$DEC_DIR"/${TODAY}*.md 2>/dev/null)
        if [ -n "$_decs" ]; then
            for f in $_decs; do echo "- $(basename "$f")"; done
        else
            echo "- (none today)"
        fi
    fi
    echo ""

    # worktree 一覧
    echo "### 🌳 worktree"
    git -C "$CWD" worktree list 2>/dev/null | while IFS= read -r line; do
        echo "- $line"
    done
    echo ""

    # 艦隊（active sessions・12h 窓）— Fleet 指揮層（spec: harness-next-level P4）
    echo "### 🛰 Fleet (active sessions)"
    _reg="$AI_BASE/sessions/registry"
    _shown=0
    if [ -d "$_reg" ] && command -v jq >/dev/null 2>&1; then
        _cutoff=$(date -u -v-12H +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null \
            || date -u -d "12 hours ago" +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || echo "0000")
        for f in "$_reg"/*.json; do
            [ -f "$f" ] || continue
            _st=$(jq -r '.status // empty' "$f" 2>/dev/null)
            [ "$_st" = "active" ] || continue
            _seen=$(jq -r '.last_seen // empty' "$f" 2>/dev/null)
            [ -n "$_seen" ] && [ "$_seen" \< "$_cutoff" ] && continue
            _a=$(jq -r '.author // "?"' "$f" 2>/dev/null)
            _b=$(jq -r '.branch // "?"' "$f" 2>/dev/null)
            _w=$(jq -r '.ws // ""' "$f" 2>/dev/null)
            echo "- ${_a} @ \`${_b}\`${_w:+ — $_w} (${_seen})"
            _shown=$((_shown + 1))
        done
    fi
    [ "$_shown" = "0" ] && echo "- (none active)"
    echo ""

    # WS 一覧（current にマーク）。新 layout（workspaces/<author>/<topic>/）優先、
    # 無ければ legacy（workspaces/*.md）。
    echo "### 🗂 Workspaces"
    _cur=""
    _curptr="$AI_BASE/WORKSPACE.md"
    command -v _ai_context_ws_pointer >/dev/null 2>&1 && _curptr=$(_ai_context_ws_pointer "$AI_BASE" "$CWD")
    [ -f "$_curptr" ] && _cur=$(grep -m1 '^# Workspace:' "$_curptr" 2>/dev/null | sed 's/^# Workspace:[[:space:]]*//')
    _author=""
    command -v _ai_context_author >/dev/null 2>&1 && _author=$(_ai_context_author "$CWD")
    if [ -n "$_author" ] && [ -d "$WS_DIR/$_author" ]; then
        for d in "$WS_DIR/$_author"/*/; do
            [ -d "$d" ] || continue
            _name=$(basename "$d")
            [ "$_name" = "old" ] && continue
            if [ "$_name" = "$_cur" ]; then echo "- **$_name** ← current"; else echo "- $_name"; fi
        done
    elif [ -d "$WS_DIR" ]; then
        for f in "$WS_DIR"/*.md; do
            [ -f "$f" ] || continue
            _name=$(basename "$f" .md)
            if [ "$_name" = "$_cur" ]; then echo "- **$_name** ← current"; else echo "- $_name"; fi
        done
    fi
    [ -z "$_cur" ] || echo ""
    echo "<!-- AUTO-DASHBOARD-END -->"
} > "$BLOCK"

# --- DASHBOARD.md へ書き出し（変化があった時だけ。無駄な mtime 更新を避ける） ---
if [ ! -f "$DASHBOARD" ] || ! cmp -s "$BLOCK" "$DASHBOARD"; then
    cat "$BLOCK" > "$DASHBOARD"
fi

# --- 旧出力先 active.md に AUTO-DASHBOARD ブロックが残存していれば1行ポインタへ置換 ---
if [ -f "$ACTIVE" ] && grep -q '<!-- AUTO-DASHBOARD-START' "$ACTIVE"; then
    NEW=$(mktemp)
    awk '
        /<!-- AUTO-DASHBOARD-START/{ print "<!-- AUTO-DASHBOARD: the overview moved to DASHBOARD.md (hook-managed, local) -->"; skip=1; next }
        /<!-- AUTO-DASHBOARD-END/{ skip=0; next }
        skip!=1 { print }
    ' "$ACTIVE" > "$NEW"
    if ! cmp -s "$NEW" "$ACTIVE"; then
        cat "$NEW" > "$ACTIVE"
    fi
    rm -f "$NEW"
fi

rm -f "$BLOCK"
exit 0
