#!/bin/sh
# pending-channel.sh — 例外（人間が見るべき checkpoint）の単一集約チャネルを管理する。
#
# 北極星「例外は checkpoint のみ」を UX で実体化する。各 hook が stderr に散発させていた
# 警告を <base>/sessions/pending/<author>.md の named section に冪等集約し、SessionStart が注入する。
#   spec: docs/specs/2026-06-10_harness-next-level（P2）
#
# Usage: pending-channel.sh <section> [cwd]
#   stdin = section 本文（markdown 行。先頭に "## 見出し" を含めて渡す）
#   stdin が空 → その section を削除（＝例外が解消されたら自動で消える）
#
# 冪等: section を in-place 置換（重複しない）。同じ本文の再呼び出しでファイル不変。
# fail-open: jq 不在 / base 解決失敗 → silent exit 0。

set -u

command -v jq >/dev/null 2>&1 || exit 0

SECTION="${1:-}"
[ -z "$SECTION" ] && exit 0
CWD="${2:-$PWD}"

PLUGIN_ROOT="${CLAUDE_PLUGIN_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
PATHS="$PLUGIN_ROOT/scripts/_ai-context-paths.sh"
[ -f "$PATHS" ] || exit 0
BASE=$(sh "$PATHS" --resolve "$CWD" 2>/dev/null)
[ -z "$BASE" ] && exit 0

# 個人状態を <author>/ で scope 化（複数人で衝突回避）。author 不明時は unknown。
AUTHOR=$(sh "$PATHS" --author "$CWD" 2>/dev/null)
[ -z "$AUTHOR" ] && AUTHOR="unknown"

DIR="$BASE/sessions/pending"
PENDING="$DIR/${AUTHOR}.md"
mkdir -p "$DIR" 2>/dev/null || exit 0

BODY=$(cat 2>/dev/null)
HEADER="# Pending Checkpoints (auto-generated by hooks / auto-cleared on resolution)"
START="<!-- PENDING:${SECTION} START -->"
END="<!-- PENDING:${SECTION} END -->"

[ -f "$PENDING" ] || printf '%s\n' "$HEADER" > "$PENDING"

TMP="$PENDING.tmp.$$"
# 既存の同名 section ブロックを除去（マーカー行も落とす）
awk -v s="$START" -v e="$END" '
    $0==s { inblk=1; next }
    $0==e { inblk=0; next }
    !inblk { print }
' "$PENDING" > "$TMP" 2>/dev/null || { rm -f "$TMP"; exit 0; }

# 本文が非空なら末尾に新ブロックを追記（空なら追記しない＝解消）
if [ -n "$BODY" ]; then
    {
        printf '%s\n' "$START"
        printf '%s\n' "$BODY"
        printf '%s\n' "$END"
    } >> "$TMP"
fi

# 変化時のみ書き戻し（無駄な mtime 更新を避ける）
if ! cmp -s "$TMP" "$PENDING" 2>/dev/null; then
    mv "$TMP" "$PENDING" 2>/dev/null || rm -f "$TMP"
else
    rm -f "$TMP"
fi

exit 0
